# Generated by Django 5.2 on 2025-06-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("matricula", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("limite_aceitavel", models.FloatField()),
                ("categoria", models.CharField(max_length=100)),
                ("requisito", models.TextField()),
                ("periodicidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("revisao", models.CharField(max_length=50)),
                ("data", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeEmpresarial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="EducacaoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tema", models.CharField(max_length=100)),
                ("atividade", models.TextField()),
                ("data_planejada", models.DateField()),
                ("data_executada", models.DateField()),
                ("total_participantes", models.IntegerField()),
                (
                    "lista_presenca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.listapresenca",
                    ),
                ),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.relatorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControleResiduo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_residuo", models.CharField(max_length=100)),
                ("nome_residuo", models.CharField(max_length=100)),
                ("data_emissao", models.DateField()),
                ("armazenagem_temporaria", models.CharField(max_length=200)),
                ("disposicao_final", models.CharField(max_length=200)),
                ("transportador", models.CharField(max_length=100)),
                ("receptor_residuo", models.CharField(max_length=100)),
                ("mtr", models.CharField(max_length=100)),
                ("cdf", models.CharField(max_length=100)),
                ("peso", models.FloatField()),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.relatorio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relatorio",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
        migrations.CreateModel(
            name="PontoMonitoramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("classificacao", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("zona_utm", models.CharField(max_length=50)),
                (
                    "unidade_empresarial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.unidadeempresarial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoramentoEfluente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_medicao", models.DateField()),
                ("resultado", models.FloatField()),
                (
                    "conformidade",
                    models.CharField(
                        choices=[
                            ("Conforme", "Conforme"),
                            ("Não Conforme", "Não Conforme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField(blank=True, null=True)),
                ("tipo_efluente", models.CharField(max_length=100)),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.parametro",
                    ),
                ),
                (
                    "ponto_monitorado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.pontomonitoramento",
                    ),
                ),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.relatorio",
                    ),
                ),
                (
                    "unidade_empresarial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.unidadeempresarial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parametro",
            name="unidade_medicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monitor.unidademedicao"
            ),
        ),
    ]
