# Generated by Django 5.2 on 2025-07-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleresiduo",
            name="unidade_empresarial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
        migrations.AddField(
            model_name="educacaoambiental",
            name="unidade_empresarial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
        migrations.AlterField(
            model_name="monitoramentoefluente",
            name="unidade_empresarial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
        migrations.AlterField(
            model_name="pontomonitoramento",
            name="unidade_empresarial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.unidadeempresarial",
            ),
        ),
    ]
