# Generated by Django 5.2 on 2025-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadeempresarial",
            name="codigo",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
