# Generated by Django 5.2 on 2025-07-14 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametro",
            name="subcategoria",
        ),
    ]
