# Generated by Django 5.2 on 2025-07-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_unidadeempresarial_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoramentoefluente",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
        migrations.AlterField(
            model_name="monitoramentoefluente",
            name="tipo_efluente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
