# Generated by Django 5.2 on 2025-07-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_controleresiduo_unidade_empresarial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleresiduo",
            name="inserido_por",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="educacaoambiental",
            name="inserido_por",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="listapresenca",
            name="inserido_por",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="monitoramentoefluente",
            name="inserido_por",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="inserido_por",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
