# Generated by Django 5.2 on 2025-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_remove_parametro_subcategoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="efluentesliquidos",
            name="justificativa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissoes",
            name="justificativa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruidos",
            name="justificativa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
