# Generated by Django 5.2 on 2025-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0003_efluentesliquidos_justificativa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="unidade",
        ),
        migrations.AddField(
            model_name="usuario",
            name="unidade",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios", to="monitor.unidadeempresarial"
            ),
        ),
    ]
