# Generated by Django 5.2 on 2025-07-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0003_alter_monitoramentoefluente_relatorio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleresiduo",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
        migrations.AlterField(
            model_name="educacaoambiental",
            name="lista_presenca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.listapresenca",
            ),
        ),
        migrations.AlterField(
            model_name="educacaoambiental",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
    ]
