# Generated by Django 5.2 on 2025-07-02 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_alter_controleresiduo_inserido_por_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoramentoefluente",
            name="inserido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="efluentes_inseridos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
