# Generated by Django 5.2 on 2025-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_remove_usuario_unidade_usuario_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="educacaoambiental",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presenca_pdfs/",
                verbose_name="Arquivo PDF",
            ),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="relatorios_pdfs/",
                verbose_name="Arquivo PDF",
            ),
        ),
    ]
