# Generated by Django 5.2 on 2025-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_alter_controleresiduo_relatorio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleresiduo",
            name="armazenagem_temporaria",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="cdf",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="data_emissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="disposicao_final",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="mtr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="peso",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="receptor_residuo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="transportador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
