# Generated by Django 5.2 on 2025-07-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0005_educacaoambiental_arquivo_pdf_relatorio_arquivo_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="efluentesliquidos",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
        migrations.AddField(
            model_name="emissoes",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
        migrations.AddField(
            model_name="ruidos",
            name="relatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.relatorio",
            ),
        ),
        migrations.AlterField(
            model_name="educacaoambiental",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="presenca_pdfs/",
                verbose_name="Inserir Lista PDF",
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="relatorios_pdfs/",
                verbose_name="Inserir Relatório PDF",
            ),
        ),
    ]
