# Generated by Django 5.2 on 2025-08-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0006_efluentesliquidos_relatorio_emissoes_relatorio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontomonitoramento",
            name="parametro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.parametro",
            ),
        ),
    ]
