# Generated by Django 5.2 on 2025-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0007_pontomonitoramento_parametro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pontomonitoramento",
            name="parametro",
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="parametro",
            field=models.ManyToManyField(blank=True, null=True, to="monitor.parametro"),
        ),
    ]
