# Generated by Django 5.2 on 2025-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0008_remove_pontomonitoramento_parametro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educacaoambiental",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
    ]
