# Generated by Django 5.2 on 2025-08-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0009_educacaoambiental_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleresiduo",
            name="codigo_residuo",
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="armazenagem_temporaria",
            field=models.CharField(
                blank=True,
                choices=[("Sim", "Sim"), ("Não", "Não")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Residuos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_residuo", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=200)),
                (
                    "classificacao",
                    models.CharField(
                        blank=True,
                        choices=[("Perigoso", "Perigoso")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.unidademedicao",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="nome_residuo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monitor.residuos"
            ),
        ),
    ]
