# Generated by Django 5.2 on 2025-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0010_remove_controleresiduo_codigo_residuo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleresiduo",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
        migrations.AddField(
            model_name="efluentesliquidos",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
        migrations.AddField(
            model_name="emissoes",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
        migrations.AddField(
            model_name="ruidos",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Documento"
            ),
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="cdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="CDF_pdfs/",
                verbose_name="Inserir CDF PDF",
            ),
        ),
    ]
