# Generated by Django 5.2 on 2025-08-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0011_controleresiduo_link_efluentesliquidos_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tratamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposicao_final", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="disposicao_final",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.tratamento",
            ),
        ),
    ]
