# Generated by Django 5.2 on 2025-08-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0012_tratamento_alter_controleresiduo_disposicao_final"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Efluentes Líquidos", "Efluentes Líquidos"),
                            ("Emissões Atmosféricas", "Emissões Atmosféricas"),
                            ("Ruídos", "Ruídos"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "subcategoria",
                    models.CharField(
                        choices=[
                            ("Diurno", "Diurno"),
                            ("Noturno", "Noturno"),
                            ("Emissão Atmosféricas", "Emissão Atmosférica"),
                            ("Qualidade do Ar", "Qualidade do Ar"),
                            ("Fumaça Preta", "Fumaça Preta"),
                            ("Efluente Industrial", "Efluente Industrial"),
                            ("Efluente Sanitário", "Efluente Sanitário"),
                            ("Efluente Pluvial", "Efluente Pluvial"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="subcategoria",
            name="programa",
        ),
        migrations.AlterField(
            model_name="controleresiduo",
            name="cdf",
            field=models.FileField(
                blank=True, null=True, upload_to="CDF_pdfs/", verbose_name="Inserir CDF"
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.classificacao",
            ),
        ),
        migrations.DeleteModel(
            name="Programa",
        ),
        migrations.DeleteModel(
            name="Subcategoria",
        ),
    ]
