# Generated by Django 5.2 on 2025-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0013_classificacao_remove_subcategoria_programa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pontomonitoramento",
            name="parametro",
        ),
        migrations.AddField(
            model_name="pontomonitoramento",
            name="subcategoria",
            field=models.ManyToManyField(
                blank=True, null=True, to="monitor.classificacao"
            ),
        ),
    ]
