# Generated by Django 5.2 on 2025-08-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0014_remove_pontomonitoramento_parametro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pontomonitoramento",
            name="subcategoria",
            field=models.ManyToManyField(blank=True, to="monitor.classificacao"),
        ),
    ]
